export const FULLSCREEN = 'FULLSCREEN';
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const UPDATE_SCATTERPLOT_DATA = 'UPDATE_SCATTERPLOT_DATA';
export const UPDATE_PLAYER_DATA = 'UPDATE_PLAYER_DATA';
